export declare const KEM_USAGES: KeyUsage[];
export declare const AEAD_USAGES: KeyUsage[];
export declare const INPUT_LENGTH_LIMIT = 128;
export declare const MINIMUM_PSK_LENGTH = 32;
export declare const EMPTY: Uint8Array;
export declare const HPKE_VERSION: Uint8Array;
export declare const SUITE_ID_HEADER_HPKE: Uint8Array;
export declare const SUITE_ID_HEADER_KEM: Uint8Array;
export declare const LABEL_DKP_PRK: Uint8Array;
export declare const LABEL_EAE_PRK: Uint8Array;
export declare const LABEL_INFO_HASH: Uint8Array;
export declare const LABEL_PSK_ID_HASH: Uint8Array;
export declare const LABEL_SECRET: Uint8Array;
export declare const LABEL_SHARED_SECRET: Uint8Array;
export declare const LABEL_KEY: Uint8Array;
export declare const LABEL_BASE_NONCE: Uint8Array;
export declare const LABEL_EXP: Uint8Array;
export declare const LABEL_SEC: Uint8Array;
export declare const LABEL_CANDIDATE: Uint8Array;
export declare const LABEL_SK: Uint8Array;
export declare const ORDER_P_256: Uint8Array;
export declare const ORDER_P_384: Uint8Array;
export declare const ORDER_P_521: Uint8Array;
