name: Cloudflare Workers CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.mdc"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/*.mdc"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: 2.x
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: Prepare test
        run: deno task npm
      - name: Run test
        run: deno task test:cloudflare
