name: Documentation CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdc"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdc"

permissions:
  contents: read

jobs:
  fmt:
    name: Run deno fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: 2.x
      - name: Check formatting
        run: deno fmt --check
