name: Documentation CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdc"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdc"

permissions:
  contents: read

jobs:
  fmt:
    name: Run deno fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.x
      - name: Check formatting
        run: deno fmt --check
